[supervisord]
nodaemon=true
user=airflow
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:api]
command=uvicorn api.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:streamlit]
command=streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:mlflow]
command=mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////app/mlflow.db --default-artifact-root /app/mlartifacts
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:airflow]
command=airflow standalone
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr